### ISSUE TITLE
App not launching

### ISSUE THREAD

**Issue by federicochiesa** [doshidak/Max#6]
As in the title, I right-clicked the app and clicked "Open" on the warning, but the app still doesn't launch. Nothing happens, just the dock resizes for a split second and then nothingness.
If I can be of any help I can send log data.

**Comment by doshidak** [comment]
Hey sorry about the late response, I've been super busy the past couple of days :(

I'm aware of this issue, I will get on it when I have the time. In the meantime, you can look at issue #5 for a temporary fix. But basically, the app immediately closes cause the compiled version is completely unsigned.
